/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const AddVisitorLog: typeof import('./src/handlers/visitor')['AddVisitorLog']
  const baseurl: typeof import('./src/handlers/utils')['baseurl']
  const fetchAuthLogin: typeof import('./src/handlers/index')['fetchAuthLogin']
  const fetchChapter: typeof import('./src/handlers/post')['fetchChapter']
  const fetchCheckToken: typeof import('./src/handlers/index')['fetchCheckToken']
  const fetchContent: typeof import('./src/handlers/utils')['fetchContent']
  const fetchContentAdmin: typeof import('./src/handlers/utils')['fetchContentAdmin']
  const fetchKeyword: typeof import('./src/handlers/index')['fetchKeyword']
  const fetchPostHtml: typeof import('./src/handlers/post')['fetchPostHtml']
  const fetchSearchOptions: typeof import('./src/handlers/index')['fetchSearchOptions']
  const fetchStatisticBook: typeof import('./src/handlers/index')['fetchStatisticBook']
  const fetchStatisticHome: typeof import('./src/handlers/index')['fetchStatisticHome']
  const fetchYiYan: typeof import('./src/handlers/vendor')['fetchYiYan']
  const getBookComment: typeof import('./src/handlers/comment')['getBookComment']
  const getBookData: typeof import('./src/handlers/index')['getBookData']
  const getBookMeta: typeof import('./src/handlers/index')['getBookMeta']
  const getDocumentComment: typeof import('./src/handlers/comment')['getDocumentComment']
  const getNav: typeof import('./src/handlers/index')['getNav']
  const getPost: typeof import('./src/handlers/post')['getPost']
  const getRandNickname: typeof import('./src/handlers/others')['getRandNickname']
  const getRandPoem: typeof import('./src/handlers/others')['getRandPoem']
  const postBookComment: typeof import('./src/handlers/index')['postBookComment']
  const postDocumentComment: typeof import('./src/handlers/comment')['postDocumentComment']
  const saveBookMeta: typeof import('./src/handlers/index')['saveBookMeta']
  const savePost: typeof import('./src/handlers/post')['savePost']
  const updateBookMeta: typeof import('./src/handlers/index')['updateBookMeta']
}
