/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackTop: typeof import('./src/components/home/BackTop.vue')['default']
    BookHeader: typeof import('./src/components/book/BookHeader.vue')['default']
    BookTabChapter: typeof import('./src/components/book/BookTabChapter.vue')['default']
    BookTabMeta: typeof import('./src/components/book/BookTabMeta.vue')['default']
    Button: typeof import('primevue/button')['default']
    FooterScript: typeof import('./src/components/common/FooterScript.vue')['default']
    HSearch: typeof import('./src/components/common/HSearch.vue')['default']
    HSearchWithDialog: typeof import('./src/components/common/HSearchWithDialog.vue')['default']
    LoginWindow: typeof import('./src/components/home/LoginWindow.vue')['default']
    Panel: typeof import('primevue/panel')['default']
    PostChapter: typeof import('./src/components/post/PostChapter.vue')['default']
    PostContent: typeof import('./src/components/post/PostContent.vue')['default']
    PostToc: typeof import('./src/components/post/PostToc.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpeedDial: typeof import('primevue/speeddial')['default']
    TheFooter: typeof import('./src/components/home/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/home/TheHeader.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    VClock: typeof import('./src/components/home/VClock.vue')['default']
    VComment: typeof import('./src/components/common/VComment.vue')['default']
    VTest: typeof import('./src/components/VTest.vue')['default']
  }
}
