/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BackTop: typeof import('./src/components/BackTop.vue')['default']
    FooterArea: typeof import('./src/components/FooterArea.vue')['default']
    HeaderArea: typeof import('./src/components/HeaderArea.vue')['default']
    HSearch: typeof import('./src/components/HSearch.vue')['default']
    HSearchWithDialog: typeof import('./src/components/HSearchWithDialog.vue')['default']
    LoginWindow: typeof import('./src/components/LoginWindow.vue')['default']
    PostChapter: typeof import('./src/components/PostChapter.vue')['default']
    PostContent: typeof import('./src/components/PostContent.vue')['default']
    PostToc: typeof import('./src/components/PostToc.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimeLine: (typeof import('./src/components/TimeLine.vue'))['default']
    VClock: typeof import('./src/components/VClock.vue')['default']
  }
}
