# 书籍地址
Resource = "E:\\Scripting\\docs-v3 - Copy"

# 数据库存储位置 Sqlite
Database = "E:\\Scripting\\docs-v3 - Copy\\main.db"

# 本地储存排序等信息
MetaFile=".meta.json"

# 端口
Addr = "8088"

Username = "admin"
Password = "admin"
