# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  api-rebuild-go:
    cmds:
      - powershell -Command "if (Test-Path 'backend\\internal\\types\\types.go') { Remove-Item 'backend\\internal\\types\\types.go' -Recurse -Force }"
      - goctl api go --api ./backend/api/main.api --dir backend
      - go run ./backend/clean/afterApiBuild.go
      - powershell -Command "if (Test-Path 'backend\internal\config') { Remove-Item 'backend\internal\config' -Recurse -Force }"
