# 书籍地址
Resource = "E:\\Scripting\\docs-v3 - Copy"

# 数据库存储位置 Sqlite
Database = "E:\\Scripting\\docs-v3 - Copy\\main.db"

# 本地储存排序等信息
MetaFile="meta.json"

# 端口
Addr = "8088"

# 初始管理员用户名与密码
Username = "admin"
Password = "admin"

# 日志等级 silent/error/warn/info
LogLevel = "silent"

# 文件夹显示内容
IntroFile = "README.md"

# API版本
ApiVersion = "v1"

# 文档版本
AppVersion = "0.0.1"
